In [29]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy
import cv2
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [30]:
minist = tf.keras.datasets.mnist
print(minist)
(x_train,y_train),(x_test,y_test)=minist.load_data()
x_train=x_train.reshape(60000,784)
y_train=y_train.reshape(60000,)
x_test.shape
x_test=x_test.reshape(10000,784)
y_test=y_test.reshape(10000,)

<module 'keras.api._v2.keras.datasets.mnist' from 'C:\\Users\\siddh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\mnist\\__init__.py'>


In [31]:
print(x_train)
x_train.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(60000, 784)

In [32]:
model=Sequential([
    Dense(units=125,activation='relu'),
    Dense(units=25,activation='relu'),
    Dense(units=10,activation='linear')
])
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics='accuracy'
)
model.fit(x_train,y_train,epochs=20)


Epoch 1/20
1875/1875 [==============================] - 9s 4ms/step - loss: 1.8382 - accuracy: 0.4696
Epoch 2/20
1875/1875 [==============================] - 8s 5ms/step - loss: 0.9698 - accuracy: 0.6657
Epoch 3/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.6203 - accuracy: 0.8191
Epoch 4/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3685 - accuracy: 0.9113
Epoch 5/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2387 - accuracy: 0.9408
Epoch 6/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1871 - accuracy: 0.9534
Epoch 7/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1487 - accuracy: 0.9621
Epoch 8/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1328 - accuracy: 0.9669
Epoch 9/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1125 - accuracy: 0.9708
Epoch 10/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.103

In [33]:
model.save("handwritten.model")

INFO:tensorflow:Assets written to: handwritten.model\assets


INFO:tensorflow:Assets written to: handwritten.model\assets


In [34]:
model=tf.keras.models.load_model("handwritten.model")

In [35]:
loss,accuracy =model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.2140 - accuracy: 0.9678
